seed: 42
builder: original # how to build the graph from raw data
# filter_str: "original_0" # filter samples containing this string in scenario_id
model:
  name: "GCNGlobal" #model type: GCN, GAT, GraphSAGE, GIN
  hidden: [64, 64]
  dropout: 0.2
  out_dim: 15
  g_dim: 18 # dimension of global feature vector
train:
  epochs: 10
  batch_size: 32 # try 16, 32, 64
  lr: 0.001
  lam: 0.5 # the weight in loss function lambda * loss_regret + (1-lambda) * loss_cls
